config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  get 'pages/user_view'

  devise_for :users
  root to: 'pages#home'

  get 'pages/aboutUs'

  get 'pages/Contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	User.primary_key = :account_no 
	belongs_to :user, :foreign_key => 'account_no'
	validate :validate_on_create

		def validate_on_create
		    if (self.receiver_account_no == self.account_no)
		      errors.add(:account_no, "Not same as your Account number")
		    end
	  end
	 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!,:configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
  stored_location_for(resource) || root_path
  end
  #   after login to user page
  def after_sign_in_path_for(resource)
	 stored_location_for(resource) || root_path
  end
  

  # customise devise add more fields
  protected
	def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username,:mobile,:f_name,:l_name,:m_name,:address,:city,:state,:addhar,:pan,:account_no,:balance,:email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username,:mobile,:f_name,:l_name,:m_name,:address,:city,:state,:addhar,:pan, :email,:account_no,:balance, :password, :current_password)}
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def user_view
  	#fetch all transaction of logined use    
   @transactions = Transaction.where('account_no = ? ', current_user.account_no).order("created_at DESC").limit(5)
   @transactions_all = Transaction.where('account_no = ? ', current_user.account_no).order("created_at DESC")
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [ :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction[:receiver_account_no] = current_user.account_no ;
    
    respond_to do |format|
      if @transaction.save
        @transaction1 = Transaction.new(transaction_params)
        @sender_user = User.find(current_user.account_no)
        @receiver_user = User.find(@transaction[:account_no])
        @sender_user.update_attributes(:balance => current_user.balance -= @transaction[:amount])
        @transaction1[:transaction_type] = 1;
        @transaction1[:account_no] = current_user.account_no;
        @transaction1[:receiver_account_no] = @transaction[:account_no] ;
        @transaction1.save
        @receiver_user.update_attributes(:balance => ( @receiver_user.balance += @transaction[:amount]))
        
        format.html { redirect_to pages_user_view_path, notice: 'Transaction successfully Done' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_no, :transaction_type,:receiver_account_no, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # display toaster message
    def toastr_flash_class(type)
        case type
        when "alert"
          "toastr.error"
        when "notice"
          "toastr.info"
        else
          "toastr.info"
        end
      end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
    
end

app/views/application/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand" href="#">Private bank limited</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="<%= 'active' if current_page?(root_path) %>  nav-item ">
              <a class="nav-link" href=<%=root_path%>>Home<span class="sr-only">(current)</span>
            </a>
            <% if user_signed_in? %>
                <li  class="<%= 'active' if current_page?(pages_user_view_path) %>  nav-item ">
                  <%= link_to "User Account".html_safe, pages_user_view_path, class:"nav-link" %>
                </li>  
            <%end%>    
            <li class="<%= 'active' if current_page?(pages_aboutUs_path) %> nav-item">
              <a class="nav-link" href=<%=pages_aboutUs_path%>>About</a>
            </li>
            <li class="<%= 'active' if current_page?(pages_Contact_path) %> nav-item">
              <a class="nav-link " href=<%=pages_Contact_path%>>Contact us</a>
            </li>
          </ul>
          <ul class="navbar-nav pull-right">
            
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Logout".html_safe, destroy_user_session_path, :method => :delete,class:"nav-link" %>
                </li>  
              <%elsif current_page?(new_user_session_path)  %>
                <li class="nav-item">
                  <%= link_to "SignUp", new_user_registration_path, class:"nav-link" %>
                </li>
              <%else%>  
                <li class="nav-item">  
                  <%= link_to "Login", new_user_session_path,class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "SignUp", new_user_registration_path, class:"nav-link" %>
                </li>  
              <% end%>
            </li>
          <ul>
        </div>
      </nav>  
      <% if notice %>
        <%= content_tag(:script) do %>
          <% flash.each do |type, message| %>
            <%= toastr_flash_class("notice") %>('<%= message %>')
          <% end %>
        <% end %>
      <% end %>
      <!-- if alert -->
      <% if alert %>
        <%= content_tag(:script) do %>
          <% flash.each do |type, message| %>
            <%= toastr_flash_class("alert") %>('<%= message %>')
          <% end %>
        <% end %>
      <% end %>
      <%= yield %>
      <footer><div class="text-center" ><label style="color:white;padding-top:6px">@Developed By Aniruddha Mirajkar</label></div></footer>
  </body>
</html>

app/views/pages/Contact.html.erb
<br>
<div class="container" style="max-width: 500px">
  <form class="form-group">
    <center>
    	<span class="form">
    		<h1>Get in touch</h1>
    	</span>
    </center>
    <div class="form-group" data-validate="Name is required">
      <input class="form-control" type="text" name="name" placeholder="Name" style="border-radius: 25px;background-color: rgb(216,216,216)" required="true">
      <span class="shadow-input1"></span>
    </div>
    <div class="form-group" data-validate="Valid email is required: ex@abc.xyz">
      <input class="form-control" type="email" name="email" placeholder="Email" style="border-radius: 25px;background-color: rgb(216,216,216)" required="true">
      <span class="shadow-input1"></span>
    </div>
    <div class="form-group" data-validate="Subject is required">
      <input class="form-control" type="text" name="subject" placeholder="Subject" style="border-radius: 25px;background-color: rgb(216,216,216)" required="true">
      <span class="shadow-input1"></span>
    </div>
    <div class="form-group" data-validate="Message is required">
      <textarea class="form-control" name="message" placeholder="Message" style="border-radius: 25px;background-color: rgb(216,216,216)" required="true">
      </textarea>
      <span class="shadow-input1"></span>
    </div>
    <div class="form-group">
      <center><button class="btn btn-primary">
          <span>
							Send Email
							<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						</span>
        </button>
      </center>
    </div>
  </form>
</div>

app/views/pages/aboutUs.html.erb
<h1>Pages#aboutUs</h1>
<p>Find me in app/views/pages/aboutUs.html.erb</p>

app/views/pages/home.html.erb
<style type="text/css">
	.carousel .carousel-item {
  height: 400px;
}

.item img {
    position: absolute;
    top: 0;
    left: 0;
    min-height: 300px;
}
</style>
	<div class="bd-example h-75">
	  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
	    <ol class="carousel-indicators">
	      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
	      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
	      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
	    </ol>
	    <div class="carousel-inner">
	      <div class="carousel-item active">
	        <img src=<%= image_path "img1.jpg" %>  class="d-block w-100" alt="...">
	        <div class="carousel-caption d-none d-md-block">
	          <h5>First slide label</h5>
	          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
	        </div>
	      </div>
	      <div class="carousel-item">
	        <img src=<%= image_path "img2.jpg" %>  class="d-block w-100" alt="...">
	        <div class="carousel-caption d-none d-md-block">
	          <h5>Second slide label</h5>
	          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	        </div>
	      </div>
	      <div class="carousel-item">
	      	<img src=<%= image_path "img3.png" %>  class="d-block w-100" alt="...">
	        <div class="carousel-caption d-none d-md-block">
	          <h5>Third slide label</h5>
	          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
	        </div>
	      </div>
	    </div>
	    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
	      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
	      <span class="carousel-control-next-icon" aria-hidden="true"></span>
	      <span class="sr-only">Next</span>
	    </a>
	  </div>
	</div>
</div>

app/views/pages/user_view.html.erb
<div class="container">
  <h1>Account Details</h1>
  <div class="row">
    <!-- Menu Start-->
    <div class="shadow p-5  col-sm-4" style="background-color:#ccffb3;height:450px">
        <div class="text-center">
            <h2>Quick Link's</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="color:white">
              <%= link_to "Transfer Funds", new_transaction_path,:class => "btn btn-info btn-lg",
              :style => "width:180px" %>
            </li>
            <li class="list-group-item" style="color:white">
                <a  title="View All " class="btn btn-info btn-lg" data-toggle="modal" data-target="#exampleModalScrollable" style="width:180px">All Transaction</a>
            </li>
            <li class="list-group-item" style="color:white">
                <a  title="Open FD/RD" class="btn btn-info btn-lg" style="width:180px">Open FD/RD</a>
            </li>
            <li class="list-group-item" style="color:white">
                <a  title="Pay Bills" class="btn btn-info btn-lg" style="width:180px">Pay Bills</a>
            </li>
        </ul>
    </div>
    <!-- Menu End-->
    <!-- Balance start-->
    <div class="shadow p-5  col-sm-4" style="background-color:pink;height:450px">
        <div class="text-center">
            <h3>Hello,<%= current_user.username%></h3>
            <h2>Account Number</h2>
            <h3><%= current_user.account_no%></h3>
            <br>
            <br>
            <h2>Balance</h2>
            <h3><%= current_user.balance%></h3>
        </div>
    </div>
    <!-- Balance start-->
    <div class="shadow p-5  col-sm-4" style="background-color:#f6bcf6;height:450px">
        <div class="text-center">
            <h2>Last Transaction</h2>
        </div>
        <table  class="table" style="overflow-y: auto;height: 350px;">
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">From/TO</th>
              <th scope="col">Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |transaction| %>
              <tr>
                <td><%=transaction.created_at.strftime("%d/%m/%Y")%></td>
                <% if transaction.transaction_type == true %>
                  <td><%=transaction.receiver_account_no%></td>
                  <td><lable style="color:red"><%=transaction.amount%></lable></td>
                <% else %>
                  <td><%=transaction.receiver_account_no%></td>
                  <td><lable style="color:green"><%=transaction.amount%></lable></td>
                <% end %>  
              </tr>
            <% end %>  
           
          </tbody>
        </table>
    </div>
  </div>
</div>

<!-- model for view all transaction -->

<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="text-center">
            <h2>Transactions</h2>
        </div>
        <table  class="table" style="overflow-y: auto;">
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">From/TO</th>
              <th scope="col">Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions_all.each do |transaction| %>
              <tr>
                <td><%=transaction.created_at%></td>
                <% if transaction.transaction_type == true %>
                  <td><%=transaction.receiver_account_no%></td>
                  <td><lable style="color:red"><%=transaction.amount%></lable></td>
                <% elsif  transaction.transaction_type == false %>
                  <td><%=transaction.receiver_account_no%></td>
                  <td><lable style="color:green"><%=transaction.amount%></lable></td>
                <% end %>  
              </tr>
            <% end %>  
           
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- model for view all transaction -->

app/views/transactions/_form.html.erb
<br>
<div class="container-fluid ">
  <center>
    <div class="card text-center" style="width: 250px">
      <div class="card-header">
        New Transaction
      </div>
      <div class="card-body">
        
        <%= form_with(model: transaction, local: true) do |form| %>
          <% if transaction.errors.any? %>
            <div id="error_explanation">
              
              <% transaction.errors.full_messages.each do |message| %>
                <li style="color: red"><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :receiver_account_Number %>
            <%= form.text_field :account_no, id: :transaction_account_no,:class => "form-control",:required =>"true" %>
             <label id="accountError" style="color: red;display:none;">Account Same as your account</label>
          </div>
          <div class="form-group">
            <%= form.text_field :receiver_account_no, id: :transaction_receiver_account_no,:hidden => "true",value: current_user.account_no %>
          </div>
          <div class="form-group">
            <%= form.check_box :transaction_type, id: :transaction_transaction_type,:hidden => "true" %>
          </div>

          <div class="form-group">
            <%= form.label :amount%>
            <%= form.text_field :amount, id: :transaction_amount,:type => "number",:min => "1",:class => "form-control",required: "true" %>
            <label id="amountError" style="color: red;display:none;">Amount Not greater than Your Balance</label>
          </div>

          <div class="actions">
            <%= form.submit "Send Money",:class => "btn btn-info",:id => "sumbit" %>
          </div>
        <% end %>

      </div>
    </div>
  </center>
</div>
<script type="text/javascript">
  $("#transaction_amount").on('change keyup paste', function() {

     if ($(this).val() > <%=current_user.balance %> ) {
        $("#amountError").css("display","block");
        $("#sumbit").attr("disabled",true); 
      }
     else
      { 
        $("#amountError").css("display","none");
        $("#sumbit").removeAttr("disabled");
      }  

      


  });
  $("#transaction_account_no").on('change keyup paste', function() {
    if ($("#transaction_account_no").val() == <%=current_user.account_no %> ) {
        $("#accountError").css("display","block");
        $("#sumbit").attr("disabled",true); 
      }
      else
      {
        $("#accountError").css("display","none");
        $("#sumbit").removeAttr("disabled");
      }
  });

</script>

app/views/transactions/new.html.erb
<%= render 'form', transaction: @transaction %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender account no:</strong>
  <%= @transaction.sender_account_no %>
</p>

<p>
  <strong>Receiver account name:</strong>
  <%= @transaction.receiver_account_name %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name),:class => "underlineHover" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name),:class => "underlineHover" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name),:class => "underlineHover" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>